# Generated by Django 2.0.5 on 2018-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceParameters',
            fields=[
                ('device_name', models.CharField(default='', max_length=1023, primary_key=True, serialize=False)),
                ('device_type', models.CharField(default='', max_length=20)),
                ('device_region', models.CharField(default='', max_length=1023)),
                ('device_isp', models.CharField(default='', max_length=1023)),
                ('event_start_time', models.CharField(default='', max_length=50)),
                ('event_end_time', models.CharField(default='', max_length=50)),
                ('event_duration', models.CharField(default='', max_length=50)),
                ('event_state', models.CharField(default='', max_length=10)),
                ('event_state_type', models.CharField(default='', max_length=10)),
                ('device_ping', models.CharField(default='OK', max_length=10)),
                ('device_packet_loss', models.CharField(default='0%', max_length=10)),
                ('device_rta', models.FloatField(default=0.0)),
                ('device_checkout_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
