# Generated by Django 2.0.6 on 2018-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('upload_file', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_name', models.CharField(default='', max_length=1023)),
                ('device_type', models.CharField(default='', max_length=20)),
                ('device_region', models.CharField(default='', max_length=1023)),
                ('device_isp', models.CharField(default='', max_length=1023)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceParameters',
            fields=[
                ('device_name', models.CharField(default='', max_length=1023)),
                ('device_type', models.CharField(default='', max_length=20)),
                ('device_region', models.CharField(default='', max_length=1023)),
                ('device_isp', models.CharField(default='', max_length=1023)),
                ('event_start_time', models.CharField(default='', max_length=50)),
                ('event_start_date', models.CharField(default='', max_length=50)),
                ('event_end_time', models.CharField(default='', max_length=50)),
                ('event_end_date', models.CharField(default='', max_length=50)),
                ('event_duration', models.CharField(default='', max_length=50)),
                ('event_state', models.CharField(default='', max_length=10)),
                ('event_state_type', models.CharField(default='', max_length=10)),
                ('device_ping', models.CharField(default='OK', max_length=10)),
                ('device_packet_loss', models.CharField(default='0%', max_length=10)),
                ('device_rta', models.CharField(default='', max_length=10)),
                ('device_checkout_time', models.CharField(default='', max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='', max_length=1023)),
                ('device_type', models.CharField(default='', max_length=20)),
                ('device_region', models.CharField(default='', max_length=1023)),
                ('device_isp', models.CharField(default='', max_length=1023)),
                ('event_start_time', models.CharField(default='', max_length=1023)),
                ('event_start_date', models.DateField()),
                ('event_end_time', models.CharField(default='', max_length=1023)),
                ('event_end_date', models.DateField()),
                ('event_duration', models.IntegerField(default=0)),
                ('event_state', models.CharField(default='', max_length=10)),
                ('event_state_type', models.CharField(default='', max_length=10)),
                ('device_ping', models.CharField(default='OK', max_length=10)),
                ('device_packet_loss', models.IntegerField(default=0)),
                ('device_rta', models.FloatField(default=0.0)),
                ('device_checkout_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
