# Generated by Django 2.0.6 on 2018-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_created=True)),
                ('upload_file', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('device_name', models.CharField(default='', max_length=1023, primary_key=True, serialize=False)),
                ('device_type', models.CharField(default='', max_length=20)),
                ('device_region', models.CharField(default='', max_length=1023)),
                ('device_isp', models.CharField(default='', max_length=1023)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='deviceparameters',
            name='event_end_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deviceparameters',
            name='event_start_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deviceparameters',
            name='device_checkout_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceparameters',
            name='device_rta',
            field=models.CharField(default='', max_length=10),
        ),
    ]
