# Generated by Django 2.0.6 on 2018-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='upload_file',
            field=models.FileField(upload_to='assets/'),
        ),
    ]
