# Generated by Django 2.0.6 on 2018-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180622_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='upload_file',
            field=models.FileField(upload_to='static/'),
        ),
    ]
