# Generated by Django 2.0.6 on 2018-06-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20180629_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='upload_file',
            field=models.FileField(upload_to='static/'),
        ),
    ]
