# Generated by Django 2.0.6 on 2018-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('username', models.CharField(default='', max_length=1023, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=1023)),
                ('full_name', models.CharField(default='', max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
